<?php

namespace SuperCMS\Leaves\Site\Basket;

use Rhubarb\Leaf\Table\Leaves\TableView;

class BasketTableView extends TableView
{
    public function printViewContent()
    {
        return parent::printViewContent(); // TODO: Change the autogenerated stub
    }

    public function getDeploymentPackage()
    {
        $package = parent::getDeploymentPackage();

        $package->resourcesToDeploy[] = __DIR__ . '/' . $this->getViewBridgeName() . '.js';

        return $package;
    }

    protected function getViewBridgeName()
    {
        return 'BasketTableViewBridge';
    }
}
